### ISSUE TITLE
Errore nelle opzoni del componente dopo salva e chiudi

### ISSUE THREAD

**Issue by flaviacarboni** [elpaso/com_albopretorio#1]
quando entro in “Opzioni” e apporto modifiche, per uscire devo cliccare su “Salva” e poi su “Chiudi”, in quanto “Salva e chiudi” mi restituisce un errore: il browser cerca la pagina “dominioindex.php/?option=com_albopretorio” (dominioindex.php senza caratteri tra dominio e index); succede sia con Chrome sia con Firefox

**Comment by elpaso** [comment]
Mi scusi, capisco che può sembrare complicato, si tratta semplicemente di creare un ticket diverso per argomenti diversi.

Potrebbe gentilmente creare un ticket separato per la richiesta 2 ?

Inoltre il titolo del ticket dovrebbe contenere una descrizione sommaria del problema.

**Comment by flaviacarboni** [comment]
D'accordo. Lascio questo ticket per il problema sul reindirizzamento dopo "Salva e chiudi" e procedo all'apertura di un nuovo ticket.
Grazie

**Comment by elpaso** [comment]
Può verificare se la patch corregge il problema?

**Comment by flaviacarboni** [comment]
Joomla non mi segnala aggiornamenti disponibili e, naturalmente, il problema rimane.

**Comment by elpaso** [comment]
La patch non è ancora disponibile come aggiornamento automatico, prima va adeguatamente testato ed è per questo che chiedo la sua collaborazione, il file è disponibile qui:

https://raw.githubusercontent.com/elpaso/com_albopretorio/a777c2332bdcb3ca12b5aa6025f6ef9c533d7f1b/plugins/system/albopretorio/albopretorio.php

**Comment by flaviacarboni** [comment]
Non avevo capito ... è la prima volta che "collaboro" in questo modo. Ho trasferito il file in administrator/components/com_albopretorio, con il risultato di avere una pagina bianca quando selezione il componente; quindi ho provato con la cartella components/com_albopretorio; in questo caso il componente è accessibile ma il problema si verifica ancora.
Spero di aver seguito la procedura giusta.
