### ISSUE TITLE
problem with albo pretorio in Joomla 3

### ISSUE THREAD

**Issue by robyrom** [elpaso/com_albopretorio#10]
I have installed Albo Pretorio 1.13 on Joomla 3 but in the backend I see com_albopretorio_SUBMENU_SEARCH_IN_TITLE instead of the normal voice and  for the categories as well.
In the front end I obtain a complete mess of data and label. I installed it twice but nothign changed. Has this version some problems? Thanks

**Comment by elpaso** [comment]
The component has only italian translations. Check your lang settings.

**Comment by robyrom** [comment]
Grazie! Il problema era proprio quello.
