### ISSUE TITLE
Richiesta chiarimenti in merito a impostazione privilegi di pubblicazione atti mediante ACL Joomla

### ISSUE THREAD

**Issue by flaviacarboni** [elpaso/com_albopretorio#2]
La situazione che ho potuto constatare è questa: se imposto, in "Permessi", “Modifica stato” su "Negata" l’addetto all’inserimento non ha facoltà di impostare la data di scadenza; se imposto “Modifica stato” su “Consentita” l’addetto può sospendere/pubblicare l’atto, cestinarlo e archiviarlo. 
Chiedo: sarebbe possibile consentire il solo inserimento degli atti (mediante il pulsante “Nuovo”, che dovrebbe essere il solo a comparire, senza quindi la possibilità di sospendere, cestinare o archiviare) con facoltà però di fissare la data di scadenza?
Preciso che NON si tratta di problema che pregiudichi la scelta di questo OTTIMO componente, che sottoporrò all'attenzione dell'istituzione presso cui lavoro.
Grazie

**Comment by elpaso** [comment]
La gestione delle date è delegata al core di Joomla! che le considera parte dello "stato" dell'oggetto, infatti modificandole è possibile modificare la pubblicazione dell'oggetto.

È da valutare quali regole inserire in modo da consentire la normale operatività senza pregiudicare la possibilità di effettuare correzioni.

Si può ipotizzare che ci siano due ruoli utente coinvolti:
- chi inserisce gli atti (con poteri limitati)
- l'amministratore (che può fare tutto)

Il primo dovrebbe poter:
- inserire un atto defininendo le date di pubblicazione
- intervenire in modifica sull'atto stesso ma solo prima che l'atto vada in pubblicazione

Si potrebbe complicare la cosa permettendo la modifica di alcuni campi (oblio?) anche dopo la fine della pubblicazione in modo da permettere di nascondere l'atto dalla vista archivio. Probabilmente questa operazione è talmente rara da non valere la pena di implementare una regola apposta, in questo caso eccezionale l'intervento di un amministratore può risolvere il problema.

Qualche altra idea?

**Comment by flaviacarboni** [comment]
Credo che chi inserisce gli atti debba avere il solo potere di inserimento, compresa però la data di fine pubblicazione, con o senza diritto all'oblio. Non dovrebbe invece poter intervenire in alcun modo dopo che l'atto è stato pubblicato (sospensione, ripubblicazione, eliminazione). Il tutto, possibilmente, senza intervento dell'amministratore.
