### ISSUE TITLE
Impossibile disabilitare l'opzione "Gestisci categorie" da Configurazione Permessi Albo pretorio

### ISSUE THREAD

**Issue by mevnad** [elpaso/com_albopretorio#3]
Volevo segnalare l'impossibilità nel disabilitare la gestione delle categorie, opzione modificabile da pannello Configurazione Permessi.
Qualsiasi impostazione assegnata alla voce Gestisci categorie non impedisce la possibilità di creare nuove categorie. Sia con la selezione impostata su "Ereditata" (quindi, Non consentita) sia con la selezione su "Negata" (Non consentita) l'accesso al pannello per la creazione di nuove categorie risulta essere sempre raggiungibile attraverso la voce di menu nella barra del Menu amministrativo:
Componenti / Albo pretorio / Categorie Albo pretorio

**Comment by elpaso** [comment]
Per come è fatto Joomla! non è possibile disabilitare il menu. Però se il plugin "System - Albo Pretorio" è attivo (come dovrebbe essere di default dato che il plugin viene automaticamente installato e attivato) l'utente viene rediretto sulla pagina principale del componente e compare il seguente messaggio:

Errore
La modifica delle categorie è proibita dalla configurazione delle ACL del componente.

Non risulta?

Il plugin è comunque in via di aggiornamento per un altro problema (vedi issue #1)

**Comment by mevnad** [comment]
Dopo aver installato l'ultima versione del componente il problema è stato risolto.

Grazie per l'ottimo lavoro!
