### ISSUE TITLE
Atto con data di pubblicazione antecedente alla data odierna rimane visibile a chi pubblica anche se impostato "Nascondi a fine pubblicazione"

### ISSUE THREAD

**Issue by flaviacarboni** [elpaso/com_albopretorio#4]
Volevo provare a vedere cosa succede dopo la data di scadenza di una pubblicazione in cui è stato selezionato "Nascondi a fine pubblicazione". Ho quindi pubblicato un atto con data 26/1, antecedente a quella odierna (la normativa prevede che si possa fare?) e fine pubblicazione 27/1. L'atto risulta "Pubblicato ma scaduto" ma, nonostante abbia scelto "Nascondi a fine pubblicazione", lo vedo ancora nell'elenco. E' normale?
Grazie

**Comment by elpaso** [comment]
In quale elenco?

**Comment by mevnad** [comment]
Ho fatto dei test simili ed effettivamente gli atti pubblicati ma scaduti, con l'opzione "nascondi a fine pubblicazione", risultano essere sempre visibili nell'elenco "Archivio".

**Comment by flaviacarboni** [comment]
Nell'elenco degli atti sospesi, archiviati o cestinati in amministrazione. Credo che colui che pubblica gli atti dovrebbe non vederli più dopo la loro scadenza (e quindi non poterli ripubblicare), altrimenti quale sarebbe la differenza tra atto scaduto con impostazione su "sì" del parametro "Nascondi a fine pubblicazione" e atto scaduto con lo stesso parametro impostato su "no". Se se baglio, cosa mi sfugge?
Grazie

**Comment by elpaso** [comment]
Premesso che sto attivamente lavorando su quella parte di codice e quindi vi chiederei di sospendere i test fino all 1.7, qui occorre capire cosa vogliamo ottenere distinguendo attentamente ciò che avviene nel Front-End (FE) e nel Back-End (BE):
- il flag "oblio" (nascondi) fa sì che l'atto scaduto non venga mostrato nelle viste archivio del FE
- il fatto di poter modificare lo stato di un atto (quindi modificando le date di pubblicazione) viene controllato da altri permessi ACL già implementati a livello di componente e di singola categoria, direi che non c'è bisogno di nuovi permessi o nuove regole
- nel BE si vede sempre tutto (ed è giusto così)

Per quanto riguarda l'archiviazione, questa è automatica quindi:
- quando un documento "scade" viene automaticamente archiviato
- se ha il flag "oblio" non viene mostrato nella vista archivio del FE anche se rimane tecnicamente "archiviato"

Sto implementando il controllo sulle date di pubblicazione in modo che non sia più possibile (tranne per gli amministratori) la modifica del documento una volta che questo è stato pubblicato.
