### ISSUE TITLE
Consentire la pubblicazione degli atti senza l'autorizzazione dell'amministratore

### ISSUE THREAD

**Issue by mevnad** [elpaso/com_albopretorio#5]
Ho notato che assegnando esclusivamente i permessi su "Accesso interfaccia amministrativa" e "crea", la creazione di nuovi atti resta in "sospeso" ed è necessario l'intervento di un amministratore per cambiare lo stato in "pubblicato".
Sarebbe possibile consentire all'utente incaricato solo della pubblicazione degli atti di completare i nuovi inserimenti e pubblicarli senza la supervisione di un amministratore? Grazie

**Comment by elpaso** [comment]
Si: occorre abilitare il permesso per modificare lo stato.

**Comment by mevnad** [comment]
Ho capito, non è possibile allora.
Grazie comunque.

**Comment by elpaso** [comment]
Veramente la mia risposta era: "SI", cioè che è possibile.

**Comment by mevnad** [comment]
Scusami, ci dev'essere stato un fraintendimento...
Io avevo chiesto se era possibile, abilitanto solo i permessi "Accesso interfaccia amministrativa" e "crea", consentire la pubblicazione di un nuovo atto senza l'intervento di un amministratore. La risposta, in questo caso, è no.
Se ho ben capito, per realizzare questa cosa è necessario abilitare, oltre ai due permessi precedenti, anche il permesso per modificare lo stato...

**Comment by mevnad** [comment]
Scusami, mi è sfuggito di aggiungere "senza abilitare il permesso per modificare lo stato", ma solo con i due permessi "Accesso interfaccia amministrativa" e "crea".
In pratica, cercavo di capire se si poteva evitare di concedere il permesso per modificare lo stato all'utente incaricato di inserire nuovi atti permettendogli di pubblicarli direttamente.

**Comment by elpaso** [comment]
Allora NO, in quanto (ovviamente) per modificare lo stato (e quindi pubblicare) occorre il relativo permesso, comunque è implementato nella 1.7 anche un controllo sulla pubblicazione che impedisce **in ogni caso** (a parte a un admin) la modifica di un documento se è in corso di pubblicazione (quindi flaggato come pubblicato e con le date di pubblicazioni che comprendono la data in cui viene fatta la modifica). C'è un solo caso da risolvere: se l'utente inserisce un documento con data di pubblicazione a partire da oggi ne perde immediatamente il controllo e non può più modificarlo. L'unica soluzione che mi viene in mente è quella di non permettere la pubblicazione di un documento con data di partenza "oggi" ma solo "domani".

**Comment by mevnad** [comment]
Ok, adesso è tutto chiaro. Riguardo alla questione di impedire la pubblicazione di un documento con data di partenza "oggi" ma solo "domani", non sono molto convinto. Nell'istituto dove lavoro (e dove spero di riuscire a far acquistare ed adottare il tuo componente), ad esempio, non sempre riesco ad avere "quel giorno in più", spesso si riducono talmente ai limiti delle scadenze che sarebbe un grosso guaio non poter pubblicare un documento con la stessa data di inserimento... Resterebbe comunque la possibilità di intervento da parte di un amministratore, giusto?

**Comment by elpaso** [comment]
Giusto: appena l'utente salva il documento con la data di oggi il documento si blocca e non può fare più nulla.

Un utente di livello admin può sempre e comunque fare tutto.

Si potrebbe anche pensare ad introdurre una ulteriore ACL che permetta la modifica di un documento in corso di pubblicazione senza dovere essere superamministratore ma sono restio ad introdurre una ulteriore complicazione.

**Comment by mevnad** [comment]
Infatti. Un super user interviene esclusivamente in caso di necessità, per il resto credo possa andar bene anche così.
