### ISSUE TITLE
Inserimento atti scaduti

### ISSUE THREAD

**Issue by mevnad** [elpaso/com_albopretorio#6]
Salve, è possibile inserire nuovi atti con data di fine pubblicazione precedente alla data attuale?

Ho provato ad inserire degli atti pubblicati e già scaduti presenti nel vecchio sito dell'amministrazione di cui sto gestendo il nuovo portale, ma non ci sono riuscito! Il messaggio d'errore che ricevo è: Salvataggio fallito con il seguente errore: Non è consentito inserire una nuova affissione con data di fine pubblicazione nel passato.

Esiste un modo per inserire questi atti scaduti? Grazie

**Comment by elpaso** [comment]
No, il controllo è implementato a livello di tabella.

Per curiosità: per quale motivo si dovrebbero inserire degli atti scaduti (quindi teoricamente non più pubblicati)?

**Comment by mevnad** [comment]
Il motivo risiede nel tentativo di ri-creare un elenco di Atti pubblicati ma già scaduti contenuti nell'albo del vecchio sito dell'amministrazione. Siccome devo istruire il personale che si occuperà di caricare gli atti nell'Albo del nuovo sito, avevo la necessità di ricostruire l'elenco degli atti scaduti per completare l'iter delle affissioni. La scadenza di alcuni atti risale a pochi giorni fa, quindi i nuovi atti da pubblicare devono fare riferimento a quei documenti pubblicati ma scaduti presenti nel vecchio sito.
Spero di essere stato un po' più chiaro adesso.

**Comment by elpaso** [comment]
Quindi, se ho capito bene, sarebbe utile in fase di setup iniziale poter ricreare i vecchi atti in modo da ricostituire un archivio del passato?
Per queste esigenze è spesso meglio scrivere un programmino di importazione.
Mi pare comunque un'esigenza abbastanza particolare ma se avete del budget a disposizione contattami in privato. Ho visto per esempio che altri hanno mantenuto il vecchio albo online nella fase di passaggio al nuovo.

**Comment by mevnad** [comment]
Si, sarebbe utile recuperare almeno gli ultimi atti, cioè quelli scaduti da pochi giorni, proprio perchè l'iter burocratico, nel caso di un bando di gara, ad esempio, prosegue nonostante la scadenza del bando stesso. Accade, quindi, che le affissioni successive ad una gara conclusa riguardino determine per le approvazioni di rito etc...
Tornando al nostro caso, dunque, nemmeno un Super User riesce ad inserire atti con date precedenti alla data di pubblicazione e/o creazione?

**Comment by elpaso** [comment]
No

**Comment by mevnad** [comment]
Ok, grazie.

In caso di disponibilità ad investire nell'acquisto di un plugin o simile per ricostruire un archivio di atti scaduti, a quale indirizzo posso contattarla per concordare i costi?

**Comment by elpaso** [comment]
info chiocciola itopen punto it

**Comment by mevnad** [comment]
Va bene, a risentirci.
