### ISSUE TITLE
Eliminare Colonna Data documento

### ISSUE THREAD

**Issue by mevnad** [elpaso/com_albopretorio#7]
Salve Alessandro, sarebbe possibile eliminare la colonna Data documento dalle viste Atti in pubblicazione e Archivio atti? Grazie

**Comment by elpaso** [comment]
Al momento no, anche qui: un piccolo contributo e si fa volentieri, l'ho scritto anche nella pagina del progetto:  http://www.itopen.it/albo-pretorio-per-joomla-3/ vedi Funzionalità e roadmap

**Comment by elpaso** [comment]
Funzionalità implementata nella versione 1.9
