### ISSUE TITLE
Anomalia nell'Ordinamento per Colonna e Limite record

### ISSUE THREAD

**Issue by mevnad** [elpaso/com_albopretorio#8]
Salve,

volevo segnalare un comportamento anomalo quando si cerca di ordinare i dati in vista "Elenco affissioni" cliccando su una qualsiasi intestazione di colonna per modificare l'ordinamento di default.

In pratica accede che al tentativo di ordinare diversamente per colonna i dati spariscono dalla tabella. Accanto al pulsante CERCA appare il pulsante ANNULLA RICERCA e nella tabella viene mostrato il testo "Nessun record trovato".

Se poi si clicca successivamente sul pulsante ANNULLA RICERCA la situazione sembra tornare alla normalità. Cioè compaiono a video tutti i dati memorizzati ed è possibile ordinare gli stessi in qualsiasi colonna.

Stessa identica cosa accade quando si sceglie di limitare il numero di record da visualizzare usando il menu a discesa (Visualizza n.) in basso a destra.

**Comment by elpaso** [comment]
con l'ultima versione? mi pareva di averlo corretto.

**Comment by mevnad** [comment]
si, l'ho riscontrato con l'ultima versione

**Comment by elpaso** [comment]
Questo problema è stato già corretto con la v. 1.3, disponibile da almeno un mese come aggiornamento automatico, ho appena caricato anche queste modifiche in git, oraquestol repository è aggiornato con le ultime modifiche.
