### ISSUE TITLE
joomla! 3.4.1 e aggiornamenti automatici Albo pretorio

### ISSUE THREAD

**Issue by mevnad** [elpaso/com_albopretorio#9]
Salve,

dopo l'aggiornamento alla versione 3.4.1 di joomla! ho notato questo avviso:

Attenzione
Aggiornamento: Non è possibile aggiornare il sito #5 "Aggiornamenti Albo Pretorio", URL: https://raw.githubusercontent.com/elpaso/com_albopretorio/master/update.xml

Come si potrà aggiornare il componente Albo pretorio in automatico?

**Comment by elpaso** [comment]
Ho appena testato 3.4.1: nessun problema. 
Il tuo server di aggiornamento è però errato, quello in uso nelle ultime versioni è 

http://www.itopen.it/joomla-updater?o=com_albopretorio
